name: Retag ECR
description: Retag an image in Amazon ECR without pulling or pushing with Docker.

inputs:
  repository-name:
    required: true
    description: "The name to use for the ECR Repository."
  source-tag:
    required: true
    description: "The source tag."
  destination-tag:
    required: true
    description: "The destination tag."

runs:
  using: composite

  steps:
    - name: Retag an image
      shell: bash
      env:
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        SOURCE_TAG: ${{ inputs.source-tag }}
        DESTINATION_TAG: ${{ inputs.destination-tag }}
      run: |
        SOURCE_DIGEST=$(aws ecr list-images --repository-name "${REPOSITORY_NAME}" \
                        --query "imageIds[?imageTag=='${SOURCE_TAG}'] | [0].imageDigest")
        DESTINATION_DIGEST=$(aws ecr list-images --repository-name "${REPOSITORY_NAME}" \
                             --query "imageIds[?imageTag=='${DESTINATION_TAG}'] | [0].imageDigest")

        if [[ "${SOURCE_DIGEST}" = "${DESTINATION_DIGEST}" ]]; then
          echo "Image already exists, skipped."
        else
          MANIFEST=$(aws ecr batch-get-image --repository-name "${REPOSITORY_NAME}" \
                     --image-ids imageTag="${SOURCE_TAG}" --query 'images[].imageManifest' --output text)

          aws ecr put-image --repository-name "${REPOSITORY_NAME}" \
          --image-tag "${DESTINATION_TAG}" --image-manifest "${MANIFEST}"
        fi
